// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindNewWords(arg1, arg2, arg3) {
  return window['go']['service']['WordService']['FindNewWords'](arg1, arg2, arg3);
}

export function GetRootByName(arg1) {
  return window['go']['service']['WordService']['GetRootByName'](arg1);
}

export function SubmitVocabulary(arg1) {
  return window['go']['service']['WordService']['SubmitVocabulary'](arg1);
}
