// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindNewWords(arg1:string,arg2:number,arg3:number):Promise<any>;

export function GetRootByName(arg1:string):Promise<any>;

export function SubmitVocabulary(arg1:Array<string>):Promise<void>;
