// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {relingo} from '../models';

export function ParseRawJSON():Promise<relingo.DictItem>;
