// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Play(arg1) {
  return window['go']['youdao']['Client']['Play'](arg1);
}
