// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserInfo() {
  return window['go']['relingo']['Client']['GetUserInfo']();
}

export function GetVocabulary(arg1, arg2) {
  return window['go']['relingo']['Client']['GetVocabulary'](arg1, arg2);
}

export function GetVocabularyList() {
  return window['go']['relingo']['Client']['GetVocabularyList']();
}

export function LockupDict(arg1) {
  return window['go']['relingo']['Client']['LockupDict'](arg1);
}

export function MasteredWords(arg1) {
  return window['go']['relingo']['Client']['MasteredWords'](arg1);
}

export function Ready() {
  return window['go']['relingo']['Client']['Ready']();
}

export function SetToken(arg1) {
  return window['go']['relingo']['Client']['SetToken'](arg1);
}

export function SubmitVocabulary(arg1) {
  return window['go']['relingo']['Client']['SubmitVocabulary'](arg1);
}
