// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DownloadCert():Promise<void>;

export function FindNewWords(arg1:string):Promise<Array<model.Word>>;

export function SubmitVocabulary(arg1:Array<string>):Promise<void>;
