// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadCert():Promise<void>;

export function FindNewWords(arg1:string,arg2:number,arg3:number):Promise<main.ListResult>;

export function SubmitVocabulary(arg1:Array<string>):Promise<void>;
