// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindNewWords(arg1) {
  return window['go']['main']['App']['FindNewWords'](arg1);
}

export function SubmitVocabulary(arg1) {
  return window['go']['main']['App']['SubmitVocabulary'](arg1);
}
