// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadCert() {
  return window['go']['main']['App']['DownloadCert']();
}

export function FindNewWords(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindNewWords'](arg1, arg2, arg3);
}

export function GetRootByName(arg1) {
  return window['go']['main']['App']['GetRootByName'](arg1);
}

export function SubmitVocabulary(arg1) {
  return window['go']['main']['App']['SubmitVocabulary'](arg1);
}
